### PR TITLE
load themes dynamically

### PR DESCRIPTION
**Pull request by megasyl**
User can manage his themes in the $DIR/images/ folder.

### CODE REVIEW

**Comment by megasyl** [comment]
I added a simple option handle to choose the style -s,--style and the number of images in the set -n--number in case you have more or less than 24 images in your theme

**Comment by megasyl** [comment]
Since I handle the number of images, I updated an improved quality for the firewatch theme and 62 images

**Comment by adi1090x** [comment]
@megasyl, Amazing job. i like the dynamic style selection idea, makes really easy to add new wallpapers.
Actually i just had the idea and i implemented it. i just wanted to have max 24 images (hourly) (i had 96 images for firewatch), so there was no need of having an number option & since there was only two options, no need of the option handler, just kept it simple.
Btw can i use that dynamic style idea, i've to manually edit the code due to conflicts, can't merge the pull request.

**Comment by megasyl** [comment]
> @megasyl, Amazing job. i like the dynamic style selection idea, makes really easy to add new wallpapers.
> Actually i just had the idea and i implemented it. i just wanted to have max 24 images (hourly) (i had 96 images for firewatch), so there was no need of having an number option & since there was only two options, no need of the option handler, just kept it simple.
> Btw can i use that dynamic style idea, i've to manually edit the code due to conflicts, can't merge the pull request.

Thanks.
Yeah, the -n option is not mandatory, it will be 24 by default.

I don't understand why you have conflict, the branch seems ready to be merged on my side.
If you want to merge another PR, do it and I'll rebase.

**Comment by adi1090x** [comment]
yeah as you can see, there are two PR's here & i want both, so sure there will be conflicts.
also i made few changes locally that i haven't pushed yet.

**Comment by megasyl** [comment]
Ok so first you want to push your changes. 
Then I will rebase my branch and you will be able to merge this PR. 
The branch of the 2nd PR will have to be rebased as well.

**Comment by adi1090x** [comment]
Alright, i've pushed the local changes i've made, mixing your and @sdushantha code.
review it and make it better if you can.

**Comment by megasyl** [comment]
Ok, I rebased my branch so you will be able to merge the branch.
Note that changed a bit the code to be able to handle both jpg and png files in themes.

**Comment by adi1090x** [comment]
Not working, also it seems to use only png images.
the number option is not working as expected, and it kinda not necessary. 
Screenshot

**Comment by megasyl** [comment]
The Bad image error seems to be system related, because it works for me on png and not on jpg.
The fix I did is just to check if the png exist, and switch to jpg if not. I don't know if there is an option on the setter to check the image before changing wallpaper, so we could catch it to choose the extension accordingly, but we could simply add an extension option on our side.

The number option seems to be working on my side. The idea is just a rule of 3 over 24 hours. The program will make a cycle of -n iterations over 24 hours. By default, NUMBER=24 so the behavior is ISO with the original implementation (0-24 images).
Now let say I only have 12 images, I want it to change every 2 hours, so my 12 images make a cycle in 24 hours.
In my case, I have 62 images in my theme, and with -n=62 the wallpaper will change every 23,2 minutes.
When you use -n=2, it means change every 12 hours, which might be cool if you have only 2 images but ...

**Comment by megasyl** [comment]
I found a way to catch the hsetroot error si it's able to change extension accordingly.

Also, about the -n option, we could set the default value as $(ls $STYLE -1 | wc -l), so the user don't have to bother about the number of images in the theme.

**Comment by megasyl** [comment]
Also, I noticed feh --bg-scale works on a multiple monitor setup, but hsetroot --fill is stretching the image. Do you want me to change it ?

**Comment by adi1090x** [comment]
Yeah, i was thinking about it... Do it, also remove the firewatchHD wallpapers, there are already two versions of that. And I'm thinking about not to make repo big, not everyone wants every wallpaper. We'll put these new wallpapers in a separate place and put a download link in readme.

**Comment by megasyl** [comment]
Done :)

**Comment by adi1090x** [comment]
okay, so i was testing your code, and i have few errors...
2020-04-27-223156_807x576_scrot

+ the `-f` option is not necessary, script already selects the jpg/png file.
+ the `-n` option should me mandatory not optional, or it'll give error.
+ Again, lets keep the old idea here... SIMPLE.

here's the perfectly working code i like -
```bash
#!/bin/bash

case "$OSTYPE" in
	linux*) DIR="$(pwd)" ;;
	*) DIR="$(pwd)" ;;
esac

case "$OSTYPE" in
	linux*) TIME="$(date +%k)" ;;
	*) TIME="$(date +%k)" ;;
esac

## For XFCE
if [ "$OSTYPE" == "linux"* ]; then
    SCREEN="$(xrandr --listactivemonitors | awk -F ' ' 'END {print $1}' | tr -d \:)"
    MONITOR="$(xrandr --listactivemonitors | awk -F ' ' 'END {print $2}' | tr -d \*+)"
fi

case "$OSTYPE" in
	linux*) if [ -n "$SWAYSOCK" ]; then SETTER="eval ogurictl output '*' --image";
	elif [[ "$DESKTOP_SESSION" =~ ^(MATE|Mate|mate)$ ]]; then SETTER="gsettings set org.mate.background picture-filename";
	elif [[ "$DESKTOP_SESSION" =~ ^(Xfce Session|xfce session|XFCE|xfce|Xubuntu|xubuntu)$ ]]; then SETTER="xfconf-query --channel xfce4-desktop --property /backdrop/screen$SCREEN/monitor$MONITOR/workspace0/last-image --set";
	elif [[ "$DESKTOP_SESSION" =~ ^(LXDE|Lxde|lxde)$ ]]; then SETTER="pcmanfm --set-wallpaper";
	elif [[ "$DESKTOP_SESSION" =~ ^(PANTHEON|Pantheon|pantheon|GNOME|Gnome|gnome|UBUNTU|Ubuntu|ubuntu|DEEPIN|Deepin|deepin)$ ]]; then SETTER="gsettings set org.gnome.desktop.background picture-uri";
	else SETTER="feh --bg-scale"; fi ;;
	*) if [ -n "$SWAYSOCK" ]; then SETTER="eval ogurictl output '*' --image";
	elif [[ "$DESKTOP_SESSION" =~ ^(MATE|Mate|mate)$ ]]; then SETTER="gsettings set org.mate.background picture-filename";
	elif [[ "$DESKTOP_SESSION" =~ ^(Xfce Session|xfce session|XFCE|xfce|Xubuntu|xubuntu)$ ]]; then SETTER="xfconf-query --channel xfce4-desktop --property /backdrop/screen$SCREEN/monitor$MONITOR/workspace0/last-image --set";
	elif [[ "$DESKTOP_SESSION" =~ ^(LXDE|Lxde|lxde)$ ]]; then SETTER="pcmanfm --set-wallpaper";
	elif [[ "$DESKTOP_SESSION" =~ ^(PANTHEON|Pantheon|pantheon|GNOME|Gnome|gnome|UBUNTU|Ubuntu|ubuntu|DEEPIN|Deepin|deepin)$ ]]; then SETTER="gsettings set org.gnome.desktop.background picture-uri";
	else SETTER="feh --bg-scale"; fi ;;
esac

STYLE=

set_wallpaper() {
  image="$DIR/images/$STYLE/$1"
  if [ $FORMAT ]; then
    $SETTER "$image.$FORMAT"
    return;
  fi
  errormessage=$($SETTER "$image.png" 2>&1)
  if [ ! -z "$errormessage" ]; then
    errormessage=$($SETTER "$image.jpg" 2>&1)
    if [ ! -z "$errormessage" ]; then
      echo "Image $TIME.jpg/.png does not exist."; exit 1;
    fi
    FORMAT="jpg"
  else
    FORMAT="png"
  fi
}

main() {
	num=$(($TIME/1))
    set_wallpaper $num && sleep 2
}

usage() {
available_styles=($(ls $DIR/images | sed 's/^/-/'))
echo -n "
Dynamic Wallpaper V1.0
Developed By - Aditya Shakya (@adi1090x)

Styles Dir: $DIR/images

"
printf "Available options:  "
printf -- '%s  ' "${available_styles[@]}"
printf -- '\n\n'
}

init() {
    while true; do
        main && exec $DIR/test.sh -$STYLE
    done
}

is_valid_style() {
    available_styles=($(ls $DIR/images | sed 's/^/-/'))
    for i in "${available_styles[@]}"
    do
        [ "$i" == "$1" ] && STYLE=$(echo "$1" | cut -d- -f 2-)
    done
}

is_valid_style "$1"

if [ "$STYLE" ]; then
    init
else
    usage
fi
```

What you say?

**Comment by megasyl** [comment]
> the -f option is not necessary, script already selects the jpg/png file.

With hsetroot to catch an error I had to run the command. If it failed, the screen would blink due to the change to a black background. Without -f the blink would repeat at every iteration.

> the -n option should me mandatory not optional, or it'll give error.

I set the default value to $(ls $STYLE -1 | wc -l), so it is automatically set for the number of images in the style, and it's still overridable. So it's not mandatory ..

I don't understand your first error with bitday, works perfectly on my side.
For the last line, with TIME=2 & NUMBER=12 it should be 1, but since I round the result it cause a lack of precision in the calculation. Increasing the scale fixes the problem: 
echo "scale=2; 2/24*12" | bc | awk '{print int($1+0.5)}' => 1

Anyway, if you don't want the changes I can just close the PR you know. I still have my fork.

**Comment by megasyl** [comment]
Ok, my bad for the first error, I made $(ls $STYLE -1 | wc -l) instead of $(ls $DIR/images/$STYLE -1 | wc -l). Fixed it, and also the scale factor. 

The usage is pretty simple that way : dwall -s=seoul would work without any tweak. Also, no need for symlinks now.

**Pull request merged**
