### PR TITLE
cleaned up the code

### PR DESCRIPTION
**Pull request by sdushantha**
- portable bash shebang
- more portable functions
- made one of the if statements a oneliner
- put quotes around some variables to prevent globing

### CODE REVIEW

**Comment by adi1090x** [comment]
@sdushantha, good job but sorry i can't merge it due to conflicts.
can i use the code, i just manually have to edit the source code?

**Comment by sdushantha** [comment]
> i can't merge it due to conflicts.

@adi1090x That is very strange, because everything seems fine on my end and ready to be merged.
image

I am more than happy to create a new PR after forking the latest version, if you keep encountering this problem.

**Comment by adi1090x** [comment]
As you can see, there are two PR's here & i want both, so sure there will be conflicts.
also i made few changes locally that i haven't pushed yet.

**Comment by sdushantha** [comment]
If you push the changes that you made made locally, and then merge #2 I can make the needed changes, to resolve the conflicts 👍 
If the changes made by @megasyl causes conflicts, I'm sure it can easily be resolved with teamwork :)

**Comment by adi1090x** [comment]
Alright, i've pushed the local changes i've made, mixing your and @megasyl code.
review it and make it better if you can.

**Comment by sdushantha** [comment]
I have resolved the conflicts. It looks like you already used my edits when you updated the code locally, therefore the only difference now is 0edf587

**Comment by adi1090x** [comment]
do you have a mac?

**Comment by sdushantha** [comment]
@adi1090x I do have a Macbook, but I currently don't have access to it, so I unfortunately can not test it at the moment.

**Pull request merged**
